# Generated by Django 3.2 on 2023-12-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0002_client_client_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_detail',
        ),
    ]
