# Generated by Django 3.2 on 2023-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0003_delete_client_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bandwdith',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ip_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
