# Generated by Django 3.2 on 2023-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='dc_app.subscription'),
        ),
    ]
