# Generated by Django 3.2 on 2023-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0006_alter_client_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bandwdith',
            new_name='bandwidth',
        ),
    ]
