# Generated by Django 3.2 on 2024-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0007_rename_bandwdith_client_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
