# Generated by Django 3.2 on 2024-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0008_auto_20240111_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
