# Generated by Django 3.2 on 2024-02-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0009_client_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='dc_app.interface'),
        ),
    ]
